export const ADD_ARTICLE="ADD_ARTICLE";
export const ADD_ARTICLE_SUCCEEDED="ADD_ARTICLE_SUCCEEDED";
export const ADD_ARTICLE_FAILED="ADD_ARTICLE_FAILED";
export const SELECT_ARTICLE="SELECT_ARTICLE";
export const DELETE_ARTICLE="DELETE_ARTICLE";
export const LOAD_ARTICLES_REQUESTED="LOAD_ARTICLES_REQUESTED";
export const LOADING_ARTICLES_FAILED="LOADING_ARTICLES_FAILED";
export const LOADING_ARTICLES_SUCCEEDED="LOADING_ARTICLES_SUCCEEDED";