export const ADD_ARTICLE="ADD_ARTICLE";
export const SELECT_ARTICLE="SELECT_ARTICLE";
export const DELETE_ARTICLE="DELETE_ARTICLE";
export const LOADING_ARTICLES="LOADING_ARTICLES";
export const LOADING_ARTICLES_FAILED="LOADING_ARTICLES_FAILED";
export const LOADING_ARTICLES_SUCCEEDED="LOADING_ARTICLES_SUCCEEDED";